# KV绑定
[[kv_namespaces]]
binding = "CLOUDNAV_KV"
id = "e1a0690745fc4b8590bc53bfe37564e8"

# R2绑定
[[r2_buckets]]
binding = "CLOUDNAV_R2"
bucket_name = "dh-wj"

[[r2_buckets]]
binding = "TRANSFER_R2_xxx"
bucket_name = "dh-wj"